name: continuous-integration-workflow.yml

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get and run the base moj spark local Docker image for testing
      run:  |
        docker build . --file Dockerfile_testrunner --tag testdocker
        docker run --rm \
          --env COVERALLS_REPO_TOKEN=${{ secrets.GITHUB_TOKEN }} --env COVERALLS_SERVICE_NAME=github \
          --env GITHUB_REF=${{ github.ref }} \
          testdocker